---
- hosts: all
  become: true
  tasks:
    # --- DÀNH CHO UBUNTU/DEBIAN ---
    - name: install apache2 package (Ubuntu)
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: update repository index (Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    # --- DÀNH CHO CENTOS/REDHAT ---
    - name: install httpd package (CentOS)
      ansible.builtin.dnf:
        name: httpd
        state: present
      when: ansible_distribution == "CentOS"


    - name: start httpd service (CentOS)
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"
