---
- hosts: all
  become: true
  tasks:
    # --- DÀNH CHO UBUNTU/DEBIAN ---
    - name: install apache, php package
      ansible.builtin.package:
        name: 
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
